[versions]
javalin = "6.7.0"
slf4j = "2.0.17"
freemarker = "2.3.34"
junit = "6.0.2"
jackson = "2.20.1"
hikari = "7.0.2"
postgresql = "42.7.9"
flyway = "11.20.2"

[libraries]
javalin-core = { module = "io.javalin:javalin", version.ref = "javalin" }
javalin-rendering = { module = "io.javalin:javalin-rendering", version.ref = "javalin" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
flyway-postgres = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }

[bundles]
app = [
    "slf4j-simple",
    "javalin-core",
    "javalin-rendering",
    "freemarker",
]
test = [
    "junit-jupiter",
    "slf4j-simple",
]
testRuntime = [
    "junit-launcher"
]
java = [
    "slf4j-api",
]

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }
